### ISSUE TITLE
02 - Kafka Configurazione

### ISSUE THREAD

**Issue by gabManolache** [gabManolache/aicof-tasks#13]
### **Apache Kafka per Notifiche**

**Definizione:**
Apache Kafka è una piattaforma di streaming distribuita progettata per gestire flussi di dati in tempo reale. Kafka è comunemente utilizzato per costruire pipeline di dati resilienti, distribuire eventi tra microservizi e garantire una comunicazione efficiente tra diversi componenti dell’applicazione. È altamente scalabile e tollerante ai guasti, rendendolo una scelta ideale per architetture di microservizi che necessitano di una gestione robusta degli eventi.

**Casi d’uso comuni:**
- Distribuzione di notifiche in tempo reale.
- Pipeline di eventi in architetture basate su microservizi.
- Sistemi di monitoraggio in tempo reale.

---

### **Configurazione di Kafka in Spring Boot**

1. **Dipendenza Maven/Gradle:**
   Aggiungi la dipendenza `spring-kafka` nel tuo file `pom.xml` o `build.gradle`.

   **Maven:**
   ```xml
   <dependency>
       <groupId>org.springframework.kafka</groupId>
       <artifactId>spring-kafka</artifactId>
   </dependency>
   ```

   **Gradle:**
   ```groovy
   implementation 'org.springframework.kafka:spring-kafka'
   ```

2. **Configurazione di Kafka nel file `application.yml` o `application.properties`:**

   Nel file `application.yml`:
   ```yaml
   spring:
     kafka:
       bootstrap-servers: localhost:9092
       consumer:
         group-id: my-group
         auto-offset-reset: earliest
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       producer:
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
   ```

   Nel file `application.properties`:
   ```properties
   spring.kafka.bootstrap-servers=localhost:9092
   spring.kafka.consumer.group-id=my-group
   spring.kafka.consumer.auto-offset-reset=earliest
   spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
   spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
   spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
   spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
   ```

3. **Codice per producer e consumer:**
   - **Producer:**
     ```java
     @Service
     public class KafkaProducerService {
         @Autowired
         private KafkaTemplate<String, String> kafkaTemplate;

         public void sendMessage(String topic, String message) {
             kafkaTemplate.send(topic, message);
         }
     }
     ```

   - **Consumer:**
     ```java
     @Service
     public class KafkaConsumerService {
         @KafkaListener(topics = "my-topic", groupId = "my-group")
         public void consume(String message) {
             System.out.println("Messaggio ricevuto: " + message);
         }
     }
     ```

---

### **Consigli per l'integrazione con Kafka**

- **Gestione degli offset**: Configura la gestione degli offset (manuale o automatica) in base alle esigenze. Se hai bisogno di un controllo preciso su quando vengono confermati i messaggi, usa il commit manuale degli offset.
  
  Esempio di commit manuale:
  ```java
  @KafkaListener(topics = "my-topic", groupId = "my-group")
  public void consume(ConsumerRecord<String, String> record, Acknowledgment acknowledgment) {
      System.out.println("Messaggio ricevuto: " + record.value());
      acknowledgment.acknowledge();  // Commit manuale
  }
  ```

- **Partizioni**: Utilizza più partizioni per migliorare le performance. Ogni partizione può essere elaborata in parallelo da diversi consumer, garantendo un throughput maggiore.

- **Resilienza**: Kafka è progettato per essere resiliente. Tuttavia, assicurati di configurare adeguatamente il numero di repliche e il livello di fattore di replica per garantire l’affidabilità in caso di guasti.

- **Ordine dei messaggi**: Kafka garantisce l'ordine dei messaggi solo all'interno delle partizioni. Se hai bisogno di garantire un ordine rigoroso, devi inviare tutti i messaggi con la stessa chiave verso la stessa partizione.

---

### **Configurazione di Docker per Kafka**

Ecco come configurare un'istanza di Kafka e Zookeeper utilizzando Docker.

1. **Crea un file `docker-compose.yml`:**

   ```yaml
   version: '2'
   services:
     zookeeper:
       image: wurstmeister/zookeeper:3.4.6
       ports:
         - "2181:2181"

     kafka:
       image: wurstmeister/kafka:2.12-2.2.1
       ports:
         - "9092:9092"
       expose:
         - "9093"
       environment:
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_CREATE_TOPICS: "my-topic:1:1" # Creazione di un topic all'avvio (my-topic con 1 partizione e 1 replica)
       volumes:
         - /var/run/docker.sock:/var/run/docker.sock
   ```

2. **Comandi per avviare Kafka con Docker:**

   Posizionati nella directory del tuo `docker-compose.yml` e avvia Kafka e Zookeeper:
   ```bash
   docker-compose up
   ```

   Questo avvierà sia Zookeeper che Kafka. Kafka sarà accessibile sulla porta `9092`.

---

### **Problematiche comuni con Kafka:**

1. **Timeout di connessione**: Se Kafka non riesce a connettersi a Zookeeper o se ci sono problemi di configurazione della rete, potresti riscontrare timeout di connessione. Verifica sempre che `KAFKA_ADVERTISED_LISTENERS` e `KAFKA_LISTENERS` siano configurati correttamente.

2. **Persistenza**: Se hai bisogno di persistenza, assicurati di configurare correttamente i volumi in Docker per Zookeeper e Kafka.

3. **Sicurezza**: Kafka di default non ha una configurazione di sicurezza abilitata. Assicurati di implementare SASL o SSL se stai lavorando in un ambiente di produzione.

---

### **Configurazione in Kubernetes**

Ecco un esempio di come configurare Kafka e Zookeeper in Kubernetes con le configurazioni di `application.yml` e i segreti:

1. **Kafka ConfigMap:**
   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: kafka-config
   data:
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
   ```

2. **Deployment di Kafka e Zookeeper:**
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: kafka
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: kafka
     template:
       metadata:
         labels:
           app: kafka
       spec:
         containers:
         - name: kafka
           image: wurstmeister/kafka:2.12-2.2.1
           envFrom:
             - configMapRef:
                 name: kafka-config
           ports:
           - containerPort: 9092
         - name: zookeeper
           image: wurstmeister/zookeeper:3.4.6
           ports:
           - containerPort: 2181
   ```

3. **Secrets e Configurazioni Kubernetes:**
   - Usa i segreti di Kubernetes per gestire le credenziali di accesso in ambienti di produzione.
   - Aggiungi parametri di sicurezza nei segreti per configurare SSL e SASL (se usi la sicurezza).

---

### **Suggerimenti**

- **Monitoraggio**: Kafka espone metriche tramite JMX. Integra strumenti come Prometheus e Grafana per monitorare lo stato e le performance di Kafka.
- **Backup**: Implementa meccanismi di backup per i log di Kafka in caso di fallimento dei nodi.
