### ISSUE TITLE
01 - swagger configurazione

### ISSUE THREAD

**Issue by gabManolache** [gabManolache/aicof-tasks#14]
### **Swagger per Documentazione delle API**

**Definizione:**
Swagger (ora noto come OpenAPI) è uno strumento ampiamente utilizzato per la documentazione interattiva delle API REST. Consente di generare automaticamente la documentazione per tutte le API esposte, e include una UI interattiva per testare gli endpoint direttamente dal browser.

In un progetto Spring Boot, Swagger aiuta a documentare chiaramente le API, mostrando dettagli come parametri, modelli di risposta e codici di stato. Tuttavia, in ambienti di produzione, può rappresentare un rischio per la sicurezza, quindi è una buona pratica limitare l'uso di Swagger solo ai profili di sviluppo (`dev`).

---

### **Configurazione di Swagger solo per il Profilo `dev`**

1. **Aggiungere la dipendenza a Swagger:**

   **Maven:**
   ```xml
   <dependency>
       <groupId>io.springfox</groupId>
       <artifactId>springfox-boot-starter</artifactId>
       <version>3.0.0</version>
   </dependency>
   ```

   **Gradle:**
   ```groovy
   implementation 'io.springfox:springfox-boot-starter:3.0.0'
   ```

2. **Creazione della configurazione Swagger per il Profilo `dev`:**

   Nella configurazione di Spring Boot, puoi abilitare Swagger solo quando il profilo attivo è `dev`. Crea una classe di configurazione Swagger annotata con `@Profile("dev")` per limitarne l'esecuzione solo in questo contesto.

   **Esempio di configurazione:**

   ```java
   import org.springframework.context.annotation.Bean;
   import org.springframework.context.annotation.Configuration;
   import org.springframework.context.annotation.Profile;
   import springfox.documentation.builders.PathSelectors;
   import springfox.documentation.builders.RequestHandlerSelectors;
   import springfox.documentation.spi.DocumentationType;
   import springfox.documentation.spring.web.plugins.Docket;
   import springfox.documentation.swagger2.annotations.EnableSwagger2;

   @Configuration
   @EnableSwagger2
   @Profile("dev")  // Swagger abilitato solo per il profilo 'dev'
   public class SwaggerConfig {

       @Bean
       public Docket api() {
           return new Docket(DocumentationType.SWAGGER_2)
               .select()
               .apis(RequestHandlerSelectors.basePackage("com.example.demo.controller"))
               .paths(PathSelectors.any())
               .build();
       }
   }
   ```

3. **Escludere Swagger dagli altri profili:**

   - Poiché la configurazione di Swagger è sotto l'annotazione `@Profile("dev")`, non sarà eseguita negli altri ambienti come `prod` o `test`. Puoi ulteriormente garantire che Swagger non venga caricato in produzione aggiungendo un flag di sicurezza nel tuo `application.yml` o `application.properties` del profilo di produzione.

   **Esempio in `application-prod.yml`:**
   ```yaml
   spring:
     swagger:
       enabled: false
   ```

   E nel file `application-dev.yml`:
   ```yaml
   spring:
     swagger:
       enabled: true
   ```

4. **Accesso alla documentazione Swagger:**

   Quando l'applicazione viene avviata con il profilo `dev`, Swagger sarà disponibile all'URL:
   ```
   http://localhost:8080/swagger-ui/index.html
   ```

---

### **Esempio di Dockerfile per Profilo Dev con Swagger**

Se stai utilizzando Docker per il deployment e desideri includere Swagger solo nel profilo `dev`, puoi configurare Docker per gestire correttamente i profili. Di seguito è riportato un esempio di `Dockerfile` che consente di impostare vari profili.

**Esempio di Dockerfile:**

```dockerfile
# Utilizza un'immagine base Java
FROM openjdk:17-jdk-alpine

# Aggiunge il JAR dell'app
COPY target/myapp.jar /app.jar

# Imposta il profilo come argomento di build
ARG PROFILE=dev

# Imposta il profilo attivo come variabile d'ambiente
ENV SPRING_PROFILES_ACTIVE=${PROFILE}

# Espone la porta
EXPOSE 8080

# Comando di esecuzione dell'applicazione Spring Boot
ENTRYPOINT ["java","-jar","/app.jar"]
```

**Esempio di `docker-compose.yml` con profilo dev:**

```yaml
version: '3'
services:
  myapp:
    build:
      context: .
      args:
        - PROFILE=dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
```

---

### **Attenzione a Swagger:**

- **Sicurezza in Produzione**: Swagger espone dettagli importanti delle tue API (inclusi endpoint e modelli). È consigliabile disabilitarlo completamente in ambienti di produzione.
  
- **Accesso Limitato**: Se vuoi mantenere Swagger anche in ambienti non di sviluppo, considera di limitare l'accesso a Swagger con autenticazione o firewalling IP.
  
- **Compatibilità**: Le versioni di Swagger e Spring Boot potrebbero non essere sempre perfettamente compatibili. Assicurati di utilizzare una versione di `springfox` compatibile con la tua versione di Spring Boot.

---

### **Kubernetes Configurazione per Swagger in dev**

Quando esegui la tua applicazione in Kubernetes con il profilo `dev`, puoi gestire il profilo attivo direttamente nei manifesti Kubernetes.

1. **ConfigMap per il profilo:**
   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: app-config
   data:
     SPRING_PROFILES_ACTIVE: dev
   ```

2. **Deployment per Kubernetes:**
   ```yaml
   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: myapp
   spec:
     replicas: 1
     selector:
       matchLabels:
         app: myapp
     template:
       metadata:
         labels:
           app: myapp
       spec:
         containers:
         - name: myapp-container
           image: myapp-image:latest
           envFrom:
             - configMapRef:
                 name: app-config
           ports:
           - containerPort: 8080
   ```

In questo modo, Swagger sarà disponibile solo quando il profilo `dev` è attivo, limitando la sua esposizione agli ambienti di sviluppo.
