### ISSUE TITLE
03 - MongoDb Configurazione

### ISSUE THREAD

**Issue by gabManolache** [gabManolache/aicof-tasks#15]
### **MongoDB per la Persistenza dei Dati**

**Definizione:**
MongoDB è un database NoSQL basato su documenti che memorizza i dati in formato BSON (Binary JSON). È utilizzato per applicazioni che richiedono alta scalabilità, flessibilità nella struttura dei dati e prestazioni elevate. MongoDB è una delle soluzioni preferite per microservizi, grazie alla sua capacità di gestire grandi quantità di dati non strutturati e di scalare orizzontalmente.

---

### **Configurazione di MongoDB in Spring Boot**

1. **Aggiungere la dipendenza a MongoDB:**

   **Maven:**
   ```xml
   <dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-data-mongodb</artifactId>
   </dependency>
   ```

   **Gradle:**
   ```groovy
   implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
   ```

2. **Configurazione in `application.yml` o `application.properties`:**

   Aggiungi la configurazione di MongoDB nel file di configurazione dell'applicazione. Assicurati di usare un profilo separato per lo sviluppo (`dev`), produzione (`prod`), ecc.

   **Esempio in `application.yml`:**
   ```yaml
   spring:
     data:
       mongodb:
         uri: mongodb://localhost:27017/mydatabase
   ```

   **Esempio in `application.properties`:**
   ```properties
   spring.data.mongodb.uri=mongodb://localhost:27017/mydatabase
   ```

3. **Esempio di codice per interagire con MongoDB:**

   Con Spring Data MongoDB, puoi creare repository MongoDB senza scrivere query SQL manuali.

   **Definizione di un documento MongoDB:**
   ```java
   import org.springframework.data.annotation.Id;
   import org.springframework.data.mongodb.core.mapping.Document;

   @Document(collection = "users")
   public class User {
       @Id
       private String id;
       private String name;
       private String email;

       // Getters e Setters
   }
   ```

   **Repository MongoDB:**
   ```java
   import org.springframework.data.mongodb.repository.MongoRepository;

   public interface UserRepository extends MongoRepository<User, String> {
       List<User> findByName(String name);
   }
   ```

   **Service per l'accesso ai dati:**
   ```java
   @Service
   public class UserService {

       @Autowired
       private UserRepository userRepository;

       public User createUser(User user) {
           return userRepository.save(user);
       }

       public List<User> getUsersByName(String name) {
           return userRepository.findByName(name);
       }
   }
   ```

---

### **Configurazione di MongoDB in Docker**

1. **Crea un file `docker-compose.yml` per MongoDB:**

   MongoDB può essere facilmente eseguito all'interno di un container Docker usando `docker-compose`. Ecco un esempio di configurazione per MongoDB:

   ```yaml
   version: '3'
   services:
     mongo:
       image: mongo:5.0
       container_name: mongo
       ports:
         - "27017:27017"
       volumes:
         - mongo_data:/data/db
       environment:
         MONGO_INITDB_ROOT_USERNAME: root
         MONGO_INITDB_ROOT_PASSWORD: example
   volumes:
     mongo_data:
   ```

2. **Comandi per avviare MongoDB con Docker:**

   Esegui il comando per avviare MongoDB:
   ```bash
   docker-compose up -d
   ```

   Questo avvierà MongoDB, accessibile sulla porta `27017`. Puoi connetterti a MongoDB utilizzando l'URI `mongodb://root:example@localhost:27017/mydatabase`.

---

### **Problematiche comuni con MongoDB:**

1. **Gestione delle connessioni**: MongoDB è altamente scalabile, ma è importante gestire correttamente le connessioni. Spring Data MongoDB utilizza un connection pool, che può essere configurato per gestire carichi elevati.

   Esempio di configurazione del connection pool:
   ```yaml
   spring:
     data:
       mongodb:
         uri: mongodb://localhost:27017/mydatabase
         connection-per-host: 100
         threads-allowed-to-block-for-connection-multiplier: 5
   ```

2. **Indici**: MongoDB non crea indici automaticamente. Aggiungi indici ai campi che verranno frequentemente cercati.

   Esempio di indicizzazione:
   ```java
   @Document(collection = "users")
   @CompoundIndexes({
       @CompoundIndex(name = "email_index", def = "{'email' : 1}", unique = true)
   })
   public class User {
       @Id
       private String id;
       private String name;
       private String email;
   }
   ```

3. **Sharding**: Se lavori con grandi quantità di dati, potresti voler implementare lo sharding (divisione orizzontale dei dati tra più server). Questo è più complesso ma può aumentare significativamente la scalabilità di MongoDB.

---

### **Configurazione di MongoDB in Kubernetes**

Per eseguire MongoDB in un cluster Kubernetes, puoi creare una risorsa StatefulSet con volumi persistenti per garantire la persistenza dei dati.

1. **MongoDB StatefulSet in Kubernetes:**

   ```yaml
   apiVersion: apps/v1
   kind: StatefulSet
   metadata:
     name: mongo
   spec:
     serviceName: mongo
     replicas: 1
     selector:
       matchLabels:
         app: mongo
     template:
       metadata:
         labels:
           app: mongo
       spec:
         containers:
         - name: mongo
           image: mongo:5.0
           ports:
           - containerPort: 27017
           volumeMounts:
           - name: mongo-data
             mountPath: /data/db
     volumeClaimTemplates:
     - metadata:
         name: mongo-data
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 1Gi
   ```

2. **Service per MongoDB:**

   Per esporre MongoDB nel cluster Kubernetes, crea un servizio:
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: mongo
   spec:
     ports:
     - port: 27017
       targetPort: 27017
     selector:
       app: mongo
   ```

3. **Secrets per le credenziali MongoDB:**

   Usa i **Secrets** di Kubernetes per gestire le credenziali di MongoDB:
   ```yaml
   apiVersion: v1
   kind: Secret
   metadata:
     name: mongo-secret
   type: Opaque
   data:
     mongo-root-username: <encoded-root-username>
     mongo-root-password: <encoded-root-password>
   ```

   Puoi ottenere i valori codificati base64 usando il comando:
   ```bash
   echo -n 'root' | base64
   echo -n 'example' | base64
   ```

---

### **Suggerimenti:**

- **Backup**: Usa strumenti come `mongodump` per creare backup regolari dei dati. Implementa volumi persistenti se esegui MongoDB in Docker o Kubernetes per garantire che i dati non vadano persi durante il riavvio del container.

- **Monitoraggio**: Integra strumenti di monitoraggio come Prometheus o Grafana per monitorare l’utilizzo della memoria, le connessioni e altri parametri importanti di MongoDB. MongoDB fornisce anche un sistema di statistiche native tramite il comando `db.stats()`.

- **Repliche**: In un ambiente di produzione, utilizza MongoDB in modalità replica set per garantire l'alta disponibilità e tolleranza ai guasti.
