### ISSUE TITLE
04 - Elastic Search Configuration

### ISSUE THREAD

**Issue by gabManolache** [gabManolache/aicof-tasks#16]
### **ElasticSearch per la Ricerca e l’Indicizzazione dei Dati**

**Definizione:**
ElasticSearch è un motore di ricerca e analisi distribuito basato su Apache Lucene. È usato principalmente per ricerche full-text, analisi in tempo reale, e per l’indicizzazione di grandi quantità di dati. ElasticSearch è spesso utilizzato per implementare funzioni di ricerca avanzate nelle applicazioni, offrendo supporto per query complesse, filtraggio, aggregazione e molto altro.

ElasticSearch è molto utile in applicazioni che richiedono ricerche veloci su dati non strutturati o semi-strutturati, come log di sistema, documenti, articoli o cataloghi di prodotti.

---

### **Configurazione di ElasticSearch in Spring Boot**

1. **Aggiungere la dipendenza a ElasticSearch:**

   **Maven:**
   ```xml
   <dependency>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
   </dependency>
   ```

   **Gradle:**
   ```groovy
   implementation 'org.springframework.boot:spring-boot-starter-data-elasticsearch'
   ```

2. **Configurazione in `application.yml` o `application.properties`:**

   Configura il tuo cluster ElasticSearch (può essere un'istanza locale o remota) specificando l'URL e la porta.

   **Esempio in `application.yml`:**
   ```yaml
   spring:
     elasticsearch:
       rest:
         uris: http://localhost:9200
   ```

   **Esempio in `application.properties`:**
   ```properties
   spring.elasticsearch.rest.uris=http://localhost:9200
   ```

3. **Creazione di un Repository ElasticSearch:**

   Con Spring Data ElasticSearch, puoi creare repository che interagiscono con ElasticSearch in modo simile a come gestisci i repository per MongoDB o JPA.

   **Esempio di entità indicizzata:**
   ```java
   import org.springframework.data.annotation.Id;
   import org.springframework.data.elasticsearch.annotations.Document;

   @Document(indexName = "products")
   public class Product {
       @Id
       private String id;
       private String name;
       private String description;
       private double price;

       // Getters e Setters
   }
   ```

   **Esempio di repository ElasticSearch:**
   ```java
   import org.springframework.data.elasticsearch.repository.ElasticsearchRepository;
   import java.util.List;

   public interface ProductRepository extends ElasticsearchRepository<Product, String> {
       List<Product> findByName(String name);
   }
   ```

4. **Esempio di un servizio per la gestione dei dati indicizzati:**
   ```java
   @Service
   public class ProductService {

       @Autowired
       private ProductRepository productRepository;

       public Product saveProduct(Product product) {
           return productRepository.save(product);
       }

       public List<Product> findByName(String name) {
           return productRepository.findByName(name);
       }
   }
   ```

---

### **Configurazione di ElasticSearch in Docker**

Per eseguire ElasticSearch in Docker, puoi usare `docker-compose` per configurare un'istanza rapidamente. Ecco un esempio di configurazione Docker per ElasticSearch.

1. **Crea un file `docker-compose.yml` per ElasticSearch:**

   ```yaml
   version: '3'
   services:
     elasticsearch:
       image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
       container_name: elasticsearch
       environment:
         - discovery.type=single-node
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
       ulimits:
         memlock:
           soft: -1
           hard: -1
       ports:
         - "9200:9200"
       volumes:
         - esdata:/usr/share/elasticsearch/data
   volumes:
     esdata:
       driver: local
   ```

2. **Comando per avviare ElasticSearch con Docker:**

   Una volta creato il file `docker-compose.yml`, puoi avviare ElasticSearch con il comando:
   ```bash
   docker-compose up -d
   ```

   Questo avvierà ElasticSearch e lo esporrà sulla porta `9200`. Puoi verificare il suo stato accedendo a `http://localhost:9200`.

---

### **Problematiche comuni con ElasticSearch:**

1. **Allocazione della memoria**: ElasticSearch utilizza molta memoria. È importante gestire correttamente le risorse di memoria, specialmente nei container Docker. Usa `ES_JAVA_OPTS` per limitare l’uso della memoria Java come indicato nel `docker-compose.yml` sopra.

2. **Manutenzione degli indici**: Gli indici possono diventare molto grandi nel tempo, specialmente quando gestisci grandi quantità di dati. ElasticSearch fornisce funzionalità di gestione degli indici, come il "rollover" degli indici e la gestione automatica dei backup. Puoi configurare la pulizia automatica dei vecchi indici con un gestore come `ElasticSearch Curator`.

3. **Distribuzione e sharding**: Se lavori in un ambiente distribuito, dovrai gestire lo sharding e il replication factor degli indici per garantire alta disponibilità e scalabilità.

4. **Ottimizzazione delle query**: Le query su ElasticSearch possono diventare complesse e richiedere risorse significative. Assicurati di utilizzare filtri, cache di query e di progettare gli indici in modo efficiente per ridurre i tempi di risposta.

---

### **Configurazione di ElasticSearch in Kubernetes**

Quando esegui ElasticSearch in Kubernetes, puoi creare un StatefulSet per gestire lo stato dell'applicazione e garantire la persistenza dei dati.

1. **ElasticSearch StatefulSet in Kubernetes:**

   ```yaml
   apiVersion: apps/v1
   kind: StatefulSet
   metadata:
     name: elasticsearch
   spec:
     serviceName: elasticsearch
     replicas: 1
     selector:
       matchLabels:
         app: elasticsearch
     template:
       metadata:
         labels:
           app: elasticsearch
       spec:
         containers:
         - name: elasticsearch
           image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
           ports:
           - containerPort: 9200
           - containerPort: 9300
           env:
           - name: discovery.type
             value: single-node
           volumeMounts:
           - name: es-data
             mountPath: /usr/share/elasticsearch/data
     volumeClaimTemplates:
     - metadata:
         name: es-data
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 5Gi
   ```

2. **Service per ElasticSearch:**

   Per esporre ElasticSearch in Kubernetes, puoi creare un servizio che lo renda accessibile ai tuoi microservizi:
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: elasticsearch
   spec:
     ports:
     - port: 9200
       targetPort: 9200
     selector:
       app: elasticsearch
   ```

---

### **Suggerimenti per l’uso di ElasticSearch:**

- **Backup e ripristino**: ElasticSearch non ha un meccanismo di backup automatico incorporato. Utilizza snapshot e repository (come un backup su S3) per garantire che i dati siano salvati regolarmente.
  
- **Monitoraggio**: ElasticSearch espone molte metriche che possono essere monitorate tramite Prometheus o altri strumenti. Monitora il consumo di risorse, lo stato dei nodi e la dimensione degli indici per evitare problemi di performance.

- **Analisi dei log**: ElasticSearch è comunemente utilizzato per la gestione dei log con lo stack ELK (ElasticSearch, Logstash, Kibana). Se hai bisogno di analizzare log e dati in tempo reale, puoi considerare di aggiungere Logstash per raccogliere ed elaborare i dati.
