### ISSUE TITLE
06 - Lombook configuration

### ISSUE THREAD

**Issue by gabManolache** [gabManolache/aicof-tasks#18]
### **MinIO per l'Archiviazione di Oggetti**

**Definizione:**
MinIO è una soluzione di archiviazione di oggetti open source compatibile con Amazon S3, utilizzata per gestire e memorizzare grandi quantità di dati come file, immagini, video, documenti e altri dati non strutturati. MinIO è spesso scelto per la sua leggerezza, facilità d'uso e compatibilità con lo standard S3, il che significa che qualsiasi applicazione che può interagire con Amazon S3 può anche funzionare con MinIO.

MinIO è particolarmente utile in architetture di microservizi che richiedono la memorizzazione e il recupero di file, mantenendo il vantaggio dell'interoperabilità con API S3 standard.

---

### **Configurazione di MinIO in Spring Boot**

1. **Aggiungere la dipendenza per MinIO:**

   Poiché MinIO è compatibile con S3, puoi usare il client AWS SDK per interagire con MinIO.

   **Maven:**
   ```xml
   <dependency>
       <groupId>software.amazon.awssdk</groupId>
       <artifactId>s3</artifactId>
       <version>2.17.67</version>
   </dependency>
   ```

   **Gradle:**
   ```groovy
   implementation 'software.amazon.awssdk:s3:2.17.67'
   ```

2. **Configurazione del client MinIO in Spring Boot:**

   Definisci le proprietà di configurazione per il client MinIO. Puoi farlo in `application.yml` o `application.properties`.

   **Esempio in `application.yml`:**
   ```yaml
   minio:
     endpoint: http://localhost:9000
     access-key: minioadmin
     secret-key: minioadmin
     bucket: mybucket
   ```

   **Esempio in `application.properties`:**
   ```properties
   minio.endpoint=http://localhost:9000
   minio.access-key=minioadmin
   minio.secret-key=minioadmin
   minio.bucket=mybucket
   ```

3. **Codice per configurare il client S3 per MinIO:**

   Configura il client S3 di Amazon per interagire con MinIO. Qui sotto un esempio di come creare e configurare un client S3 in Spring Boot:

   **Esempio di configurazione:**
   ```java
   import org.springframework.beans.factory.annotation.Value;
   import org.springframework.context.annotation.Bean;
   import org.springframework.context.annotation.Configuration;
   import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
   import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
   import software.amazon.awssdk.regions.Region;
   import software.amazon.awssdk.services.s3.S3Client;
   import software.amazon.awssdk.services.s3.S3Configuration;

   import java.net.URI;

   @Configuration
   public class MinioConfig {

       @Value("${minio.endpoint}")
       private String minioEndpoint;

       @Value("${minio.access-key}")
       private String accessKey;

       @Value("${minio.secret-key}")
       private String secretKey;

       @Bean
       public S3Client s3Client() {
           return S3Client.builder()
                   .endpointOverride(URI.create(minioEndpoint))
                   .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(accessKey, secretKey)))
                   .region(Region.US_EAST_1)  // MinIO ignora la regione, ma è obbligatoria nel client S3
                   .serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(true).build())
                   .build();
       }
   }
   ```

4. **Utilizzo del client S3 per interagire con MinIO:**

   Una volta configurato il client, puoi utilizzarlo per eseguire operazioni su MinIO, come il caricamento, il recupero e la cancellazione di file.

   **Esempio di caricamento di un file:**
   ```java
   import software.amazon.awssdk.services.s3.model.PutObjectRequest;
   import software.amazon.awssdk.services.s3.model.PutObjectResponse;

   @Service
   public class MinioService {

       @Autowired
       private S3Client s3Client;

       @Value("${minio.bucket}")
       private String bucketName;

       public void uploadFile(String key, Path filePath) {
           PutObjectRequest request = PutObjectRequest.builder()
               .bucket(bucketName)
               .key(key)
               .build();

           PutObjectResponse response = s3Client.putObject(request, filePath);
           System.out.println("File caricato con successo: " + response);
       }
   }
   ```

---

### **Configurazione di MinIO in Docker**

MinIO è spesso distribuito tramite Docker, che lo rende facile da configurare e gestire. Ecco come eseguire MinIO utilizzando Docker.

1. **Crea un file `docker-compose.yml` per MinIO:**

   ```yaml
   version: '3'
   services:
     minio:
       image: minio/minio
       container_name: minio
       ports:
         - "9000:9000"
         - "9001:9001"
       volumes:
         - ./data:/data
       environment:
         - MINIO_ROOT_USER=minioadmin
         - MINIO_ROOT_PASSWORD=minioadmin
       command: server /data --console-address ":9001"
   ```

2. **Avvia MinIO con Docker:**

   Esegui il comando per avviare MinIO:
   ```bash
   docker-compose up -d
   ```

   Dopo aver avviato MinIO, l'interfaccia web sarà disponibile su `http://localhost:9001` e l'endpoint S3 su `http://localhost:9000`.

3. **Accesso a MinIO tramite l'interfaccia web:**

   Puoi accedere alla dashboard web di MinIO per gestire i bucket e gli oggetti tramite il browser:
   ```
   http://localhost:9001
   ```

   Usa le credenziali configurate (`minioadmin/minioadmin`).

---

### **Problematiche comuni con MinIO:**

1. **Gestione delle credenziali**: Non esporre le credenziali `access-key` e `secret-key` direttamente nel codice sorgente. Usa variabili d'ambiente o i segreti di Kubernetes per gestire queste credenziali in modo sicuro.
   
2. **Performance con grandi quantità di dati**: MinIO è ottimizzato per gestire grandi quantità di dati, ma è importante configurare adeguatamente i volumi persistenti (in Docker o Kubernetes) per evitare la perdita di dati.

3. **Limitazioni della compatibilità S3**: Sebbene MinIO sia compatibile con S3, potrebbero esserci alcune funzionalità di S3 che non sono completamente supportate. Assicurati di testare tutte le funzionalità necessarie per la tua applicazione.

---

### **Configurazione di MinIO in Kubernetes**

Quando distribuisci MinIO in Kubernetes, puoi creare un StatefulSet con volumi persistenti per memorizzare i dati.

1. **MinIO StatefulSet in Kubernetes:**

   ```yaml
   apiVersion: apps/v1
   kind: StatefulSet
   metadata:
     name: minio
   spec:
     serviceName: minio
     replicas: 1
     selector:
       matchLabels:
         app: minio
     template:
       metadata:
         labels:
           app: minio
       spec:
         containers:
         - name: minio
           image: minio/minio
           args:
             - server
             - /data
           env:
           - name: MINIO_ROOT_USER
             valueFrom:
               secretKeyRef:
                 name: minio-secrets
                 key: minio-root-user
           - name: MINIO_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: minio-secrets
                 key: minio-root-password
           ports:
           - containerPort: 9000
           - containerPort: 9001
           volumeMounts:
           - name: minio-data
             mountPath: /data
     volumeClaimTemplates:
     - metadata:
         name: minio-data
       spec:
         accessModes: ["ReadWriteOnce"]
         resources:
           requests:
             storage: 10Gi
   ```

2. **Service per MinIO:**

   Per esporre MinIO nel cluster Kubernetes, crea un servizio:
   ```yaml
   apiVersion: v1
   kind: Service
   metadata:
     name: minio
   spec:
     ports:
     - port: 9000
       targetPort: 9000
     - port: 9001
       targetPort: 9001
     selector:
       app: minio
   ```

3. **Secrets per le credenziali di MinIO:**

   Usa **secrets** di Kubernetes per proteggere le credenziali di accesso:
   ```yaml
   apiVersion: v1
   kind: Secret
   metadata:
     name: minio-secrets
   type: Opaque
   data:
     minio-root-user: bWluaW9hZG1pbg==  # minioadmin
     minio-root-password: bWluaW9hZG1pbg==  # minioadmin
   ```
